// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/digitalocean/tester/db (interfaces: DB)
//
// Generated by this command:
//
//	mockgen -package=db -destination=db/db_mock.go github.com/digitalocean/tester/db DB
//

// Package db is a generated GoMock package.
package db

import (
	context "context"
	reflect "reflect"
	time "time"

	tester "github.com/digitalocean/tester"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// AddTest mocks base method.
func (m *MockDB) AddTest(ctx context.Context, test *tester.Test) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTest", ctx, test)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTest indicates an expected call of AddTest.
func (mr *MockDBMockRecorder) AddTest(ctx, test any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTest", reflect.TypeOf((*MockDB)(nil).AddTest), ctx, test)
}

// CompleteRun mocks base method.
func (m *MockDB) CompleteRun(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteRun", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteRun indicates an expected call of CompleteRun.
func (mr *MockDBMockRecorder) CompleteRun(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteRun", reflect.TypeOf((*MockDB)(nil).CompleteRun), ctx, id)
}

// DeleteRun mocks base method.
func (m *MockDB) DeleteRun(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRun", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRun indicates an expected call of DeleteRun.
func (mr *MockDBMockRecorder) DeleteRun(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRun", reflect.TypeOf((*MockDB)(nil).DeleteRun), ctx, id)
}

// EnqueueRun mocks base method.
func (m *MockDB) EnqueueRun(ctx context.Context, run *tester.Run) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueRun", ctx, run)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueRun indicates an expected call of EnqueueRun.
func (mr *MockDBMockRecorder) EnqueueRun(ctx, run any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueRun", reflect.TypeOf((*MockDB)(nil).EnqueueRun), ctx, run)
}

// FailRun mocks base method.
func (m *MockDB) FailRun(ctx context.Context, id uuid.UUID, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailRun", ctx, id, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailRun indicates an expected call of FailRun.
func (mr *MockDBMockRecorder) FailRun(ctx, id, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailRun", reflect.TypeOf((*MockDB)(nil).FailRun), ctx, id, errorMessage)
}

// GetRun mocks base method.
func (m *MockDB) GetRun(ctx context.Context, id uuid.UUID) (*tester.Run, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRun", ctx, id)
	ret0, _ := ret[0].(*tester.Run)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRun indicates an expected call of GetRun.
func (mr *MockDBMockRecorder) GetRun(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRun", reflect.TypeOf((*MockDB)(nil).GetRun), ctx, id)
}

// GetTest mocks base method.
func (m *MockDB) GetTest(ctx context.Context, id uuid.UUID) (*tester.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTest", ctx, id)
	ret0, _ := ret[0].(*tester.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTest indicates an expected call of GetTest.
func (mr *MockDBMockRecorder) GetTest(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTest", reflect.TypeOf((*MockDB)(nil).GetTest), ctx, id)
}

// Init mocks base method.
func (m *MockDB) Init(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockDBMockRecorder) Init(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockDB)(nil).Init), ctx)
}

// ListFinishedRuns mocks base method.
func (m *MockDB) ListFinishedRuns(ctx context.Context, limit int) ([]*tester.Run, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFinishedRuns", ctx, limit)
	ret0, _ := ret[0].([]*tester.Run)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFinishedRuns indicates an expected call of ListFinishedRuns.
func (mr *MockDBMockRecorder) ListFinishedRuns(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFinishedRuns", reflect.TypeOf((*MockDB)(nil).ListFinishedRuns), ctx, limit)
}

// ListPendingRuns mocks base method.
func (m *MockDB) ListPendingRuns(ctx context.Context) ([]*tester.Run, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingRuns", ctx)
	ret0, _ := ret[0].([]*tester.Run)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingRuns indicates an expected call of ListPendingRuns.
func (mr *MockDBMockRecorder) ListPendingRuns(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingRuns", reflect.TypeOf((*MockDB)(nil).ListPendingRuns), ctx)
}

// ListRunSummariesInRange mocks base method.
func (m *MockDB) ListRunSummariesInRange(ctx context.Context, begin, end time.Time, window time.Duration) ([]*tester.RunSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunSummariesInRange", ctx, begin, end, window)
	ret0, _ := ret[0].([]*tester.RunSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRunSummariesInRange indicates an expected call of ListRunSummariesInRange.
func (mr *MockDBMockRecorder) ListRunSummariesInRange(ctx, begin, end, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunSummariesInRange", reflect.TypeOf((*MockDB)(nil).ListRunSummariesInRange), ctx, begin, end, window)
}

// ListRunsForPackage mocks base method.
func (m *MockDB) ListRunsForPackage(ctx context.Context, pkg string, limit int) ([]*tester.Run, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunsForPackage", ctx, pkg, limit)
	ret0, _ := ret[0].([]*tester.Run)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRunsForPackage indicates an expected call of ListRunsForPackage.
func (mr *MockDBMockRecorder) ListRunsForPackage(ctx, pkg, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunsForPackage", reflect.TypeOf((*MockDB)(nil).ListRunsForPackage), ctx, pkg, limit)
}

// ListTests mocks base method.
func (m *MockDB) ListTests(ctx context.Context, limit int) ([]*tester.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTests", ctx, limit)
	ret0, _ := ret[0].([]*tester.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTests indicates an expected call of ListTests.
func (mr *MockDBMockRecorder) ListTests(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTests", reflect.TypeOf((*MockDB)(nil).ListTests), ctx, limit)
}

// ListTestsForPackage mocks base method.
func (m *MockDB) ListTestsForPackage(ctx context.Context, pkg string, limit int) ([]*tester.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTestsForPackage", ctx, pkg, limit)
	ret0, _ := ret[0].([]*tester.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTestsForPackage indicates an expected call of ListTestsForPackage.
func (mr *MockDBMockRecorder) ListTestsForPackage(ctx, pkg, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTestsForPackage", reflect.TypeOf((*MockDB)(nil).ListTestsForPackage), ctx, pkg, limit)
}

// ListTestsForPackageInRange mocks base method.
func (m *MockDB) ListTestsForPackageInRange(ctx context.Context, pkg string, begin, end time.Time) ([]*tester.Test, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTestsForPackageInRange", ctx, pkg, begin, end)
	ret0, _ := ret[0].([]*tester.Test)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTestsForPackageInRange indicates an expected call of ListTestsForPackageInRange.
func (mr *MockDBMockRecorder) ListTestsForPackageInRange(ctx, pkg, begin, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTestsForPackageInRange", reflect.TypeOf((*MockDB)(nil).ListTestsForPackageInRange), ctx, pkg, begin, end)
}

// ResetRun mocks base method.
func (m *MockDB) ResetRun(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetRun", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetRun indicates an expected call of ResetRun.
func (mr *MockDBMockRecorder) ResetRun(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetRun", reflect.TypeOf((*MockDB)(nil).ResetRun), ctx, id)
}

// StartRun mocks base method.
func (m *MockDB) StartRun(ctx context.Context, id uuid.UUID, runner string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartRun", ctx, id, runner)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartRun indicates an expected call of StartRun.
func (mr *MockDBMockRecorder) StartRun(ctx, id, runner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRun", reflect.TypeOf((*MockDB)(nil).StartRun), ctx, id, runner)
}
